[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/*',
    'pallets/staking/rpc',
    'pallets/staking/rpc/runtime-api',
    'primitives',
    'support',
    'runtime',
]
