[package]
name = "pallet-rewards"
version = "0.1.0"
authors = ["yxf <yxf4559@gmail.com>"]
edition = "2018"


[dependencies]
log = "0.4.8"
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
frame-support = { version = "2.0.1", default-features = false }
frame-system = { version = "2.0.1", default-features = false }
sp-std = { version = "2.0.1", default-features = false }
sp-core = { version = "2.0.1", default-features = false }
sp-runtime = { version = "2.0.1", default-features = false }
pallet-aura = { version = "2.0.1", default-features = false }
pallet-session = { version = "2.0.1", default-features = false }
sp-consensus-aura = { version = "0.8.0", default-features = false }
frame-benchmarking = { version = "2.0.1", default-features = false, optional = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
]
runtime-benchmarks = ["frame-benchmarking"]